### ISSUE TITLE
Add the featured posts by a user on profile page

### ISSUE THREAD

**Issue by Arnav-Bhardwaj** [Songtone/SOEN341TEAMF#102]
Fetch the featured posts from the front page and place in on the "User's" profile page

**Comment by MBastiampillai** [comment]
I had a discussion with Mohammad about the other issue I was tasked with. We're starting to realize that it is a bit more complicated than what was first envisioned. Further collaboration will be done tomorrow on that particular issue, before work on this is done.

**Comment by Songtone** [comment]
This is a duplicate
