### ISSUE TITLE
As a user, I would like to be add a profile picture to my account

### ISSUE THREAD

**Issue by SiamakSamie** [Songtone/SOEN341TEAMF#104]
Add the option that allows a user to add their profile picture

**Story Points:** 4

**Comment by DJNGattuso** [comment]
Acceptance test:
1) Click the "Fill Profile"
2) Fill the form and add a URL for a picture
3) Go to the Profile Page
4) Check to make sure that the picture is correct

**Comment by DJNGattuso** [comment]
Issue merged in #111
