### ISSUE TITLE
The sub category does not show up on the card.

### ISSUE THREAD

**Issue by Songtone** [Songtone/SOEN341TEAMF#109]
It will show up when you edit the post.

**Story Points:** 0

**Acceptance Test:**
On each "Want" post, at the top of the container card, the subcategory field should be visible.

**Comment by MBastiampillai** [comment]
Hey I tried the code and it looks like the subcategory no longer updates when the user edits .

**Comment by mohghalayini** [comment]
Fixed in #112

Acceptance Test **PASSED**
