### ISSUE TITLE
As user, I would like to have Register, Sign In and Profile functionality on this website.

### ISSUE THREAD

**Issue by DJNGattuso** [Songtone/SOEN341TEAMF#11]
Story Points: 13

Task Breakdown:

- #11 Create a user account in the login section
Story Points: 3
- #27 Viewing permissions based on logged in or not
Story Points: 3
- #27 Password strength
Story Points: 2
- #13 Log out
Story Points: 1
- #39 Display username text on Profile page
Story Points: 1
- #39 Display skills list on Profile page
Story Points: 1
- #39 Display a picture on Profile page
Story Points: 2

Bugs:

- #12 #22 Account not being created in database

**Comment by Songtone** [comment]
I am very happy to announce that this task is already completed! It has been done in sprint 1

**Comment by JKukulsky** [comment]
This issue is now being used as the main User Feature (parent issue) for user accounts.

**Comment by JKukulsky** [comment]
@MBastiampillai this is the main user-feature which will house your Profile features as sub-features.

**Comment by JKukulsky** [comment]
All sub-features complete.
