### ISSUE TITLE
Modification of text on buttons 

### ISSUE THREAD

**Issue by MBastiampillai** [Songtone/SOEN341TEAMF#110]
The like button  should change to unlike if the user has already like the post.
the want button should change to " I no longer want this" if  the user already clicked on I want this,

**Comment by JKukulsky** [comment]
Hi @MBastiampillai. Be sure to use all necessary Labels for this Issue. And set the Milestone to Sprint 4.

**Comment by JKukulsky** [comment]
This Issue is obsolete and will now be closed.
