### ISSUE TITLE
Coding Quality Guidelines

### ISSUE THREAD

**Issue by Arnav-Bhardwaj** [Songtone/SOEN341TEAMF#125]
Following are the set standard project guidelines

**Comment by Arnav-Bhardwaj** [comment]
@SiamakSamie could you do this as well ? just state using the code to make variable name.. camel case

**Comment by SiamakSamie** [comment]
No stupid names, camelCase. You want me to get specific? 

Routing should all be done in routes page. If you want to route something on an event in it's own js file, use flowrouter.go to specifiy new link and then complete route in routes.js. All blaze layouts renders should be done in the same place. 

All Templates should have its own page and be put in the templates folder.

All events triggered at a specific page should be handled in that page's own js file. ex: all events that occur in the post template should be in post.js. All these js files should be placed in a js folder inside of client. (This is not currently the case for some of the code and it should be fixed).

Every template should have its own css file. Also not currently the case but it should be. 

All new collections need to be specified in the collections.js file inside of the lib folder.

**Comment by Songtone** [comment]
Coding section is done. This can be now closed.
