### ISSUE TITLE
As a user I would like to see an Ad page so that I can view more details of the specific Ad.

### ISSUE THREAD

**Issue by JKukulsky** [Songtone/SOEN341TEAMF#129]
Each "Want" should have a page, similar to how each "User" has a user page.
This page shall display all Ad info, including Title, Category, subcategory, Date, Ad description, as well as who also "wants" the Ad, and who will "make" the Ad.

ex.
1. Click on the Title of the Ad to bring you to a new page, called the Ad Page.
2. New Ad page will contain all info from Ad card on the Main page.
3. We will be able to add pictures to the Ad page, to accommodate the Ad description.

**Branch:** dev/adPageInfo

**Story Points:** 20*

**Child Issues:** 
Click on the Title of the Ad to bring you to a new page, called the Ad Page. #130
Populate the Ad page with its relevant data from Ad card on the Main page. #131
Add ability to add Pictures to the Ad page, to accommodate the Ad description. #132
#134

**Acceptance Test:** All child-issues completed.

*(update according to child issues)

**Comment by Arnav-Bhardwaj** [comment]
Parent can be closed now.
