### ISSUE TITLE
Click on the Title of the Ad to bring you to a new page, called the Ad Page.

### ISSUE THREAD

**Issue by JKukulsky** [Songtone/SOEN341TEAMF#130]
Create an Ad page.
Route a button press to the new Ad page.

**Comment by Arnav-Bhardwaj** [comment]
Resolved

**Comment by JKukulsky** [comment]
@Arnav-Bhardwaj, this is not how you close an issue. 
Don't forget the important closing information.

Acceptance Test **PASSED**

Merged into master: Addition of Ad page to view more details of a specific Ad #144
