### ISSUE TITLE
Populate the Ad page with its relevant data from Ad card on the Main page.

### ISSUE THREAD

**Issue by Arnav-Bhardwaj** [Songtone/SOEN341TEAMF#131]
Ad information should be retrieved from the "wants" collection Wants. Then this data should be displayable on the Ad Page.

**Story Points:** 5

**Acceptance test:**

Click on the title of an Ad on the main page
You should be brought to a new page, called the Ad page
The page should be populated with the Ad info
Check to make sure that all data is displayed

**Comment by JKukulsky** [comment]
Use flowRouter to pass in information

**Comment by Arnav-Bhardwaj** [comment]
Issue is Resolved

**Comment by JKukulsky** [comment]
Acceptance Test **PASSED**

Merged into master: Addition of Ad page to view more details of a specific Ad #144
