### ISSUE TITLE
Add ability to add Pictures to the Ad page, to accommodate the Ad description.

### ISSUE THREAD

**Issue by JKukulsky** [Songtone/SOEN341TEAMF#132]
A user should be able to add Pictures to the Ad page to shed more light on what they want to be done.
This is to be thought of as reference material for what they "Want".

ex post.
I would like a Chess Board, made with a sliding drawer to contain all of the game pieces. I had this style in mind:
![screen shot 2017-11-08 at 10 46 51 pm](https://user-images.githubusercontent.com/25468272/32587506-cb1f2412-c4d6-11e7-9fcf-179d10ecef71.png)

**Comment by Arnav-Bhardwaj** [comment]
Feature is added.
