### ISSUE TITLE
Expand the search bar to include the drop down with categories

### ISSUE THREAD

**Issue by Arnav-Bhardwaj** [Songtone/SOEN341TEAMF#135]
@DarrinFong  could you start working on this please 
👍

**Comment by DarrinFong** [comment]
Acceptance criteria evaluation:
- Drop-down menu is present on the search bar
- Clicking on drop-down item will restrict the search to only the category selected
- Typing into the search bar and pressing enter will return top 20 relevant search results (Past issue)
- Search will automatically sort items from most liked (Past issue)

**Comment by DarrinFong** [comment]
Implementation with branch "dev/SearchDropdown", commit 55a8616

New PR created #141

**Comment by DarrinFong** [comment]
Acceptance criteria evaluation:
- [x] Drop-down menu is present on the search bar
- [x] Clicking on drop-down item will restrict the search to only the category selected
- [x] Typing into the search bar and pressing enter will return top 20 relevant search results (Past issue)
- [x] Search will automatically sort items from most liked (Past issue)
