### ISSUE TITLE
CSS implementation for the profile page

### ISSUE THREAD

**Issue by MBastiampillai** [Songtone/SOEN341TEAMF#138]
Implementing the CSS for the profile page so that it shares the same style and format as the rest of the site.

**Comment by Arnav-Bhardwaj** [comment]
@MBastiampillai Could you post us with some progress on this issue please , Thanks

**Comment by MBastiampillai** [comment]
In the code, a box with a shadow was added to that it encapsulates the credentials of the user. The wooden background that was used in the css throughout the rest of the page was used as the background again. As of now, the background appears but the credentials do not and two white boxes appear at the top, left and right respectively. Will continue working on ti to fix this bug.

**Comment by MBastiampillai** [comment]
The code I suspect to be bugging was added to my branch. If anyone has any idea about what the issue might be, can you please let me know?

**Comment by MBastiampillai** [comment]
Bug has been fixed. Background added to the two different containers are visible now. The font for the tiles in the credentials area have been stylized. The work has been updated in the EnhancedProfilePage branch.

**Comment by MBastiampillai** [comment]
The issue was solved and the pull request was merged.
