### ISSUE TITLE
Create a simple Delete/Remove Function to remove entries from the database

### ISSUE THREAD

**Issue by DJNGattuso** [Songtone/SOEN341TEAMF#19]
Merge request: #73

Need to be assigned to a parent feature in sprint 3.

Be sure that you observe your entry removals in the Viewing List on the front page. (Consult https://www.youtube.com/watch?v=9494-2E4riQ)

**Comment by Arnav-Bhardwaj** [comment]
[This is sub feature of following issue](https://github.com/Songtone/SOEN341TEAMF/issues/14)  should be deleted nick, thank you

**Comment by JKukulsky** [comment]
Delete functionality remains to be implemented. @SiamakSamie

**Comment by JKukulsky** [comment]
Don't do any new dev on here before I fix the conflicts.

**Comment by SiamakSamie** [comment]
Some features need to be applied to this. Only the creator of a post should be able to delete this. Also, the deleting option should only be availbale in profile page (to be created))
