### ISSUE TITLE
Create a simple Add Function to add entries into the database.

### ISSUE THREAD

**Issue by DJNGattuso** [Songtone/SOEN341TEAMF#20]
Be sure that you observe your entry additions in the Viewing List on the front page. (Consult https://www.youtube.com/watch?v=9494-2E4riQ)

**Comment by Arnav-Bhardwaj** [comment]
[This is sub feature of following issue](https://github.com/Songtone/SOEN341TEAMF/issues/14)  should be deleted nick, thank you

**Comment by Songtone** [comment]
@Arnav-Bhardwaj, @JKukulsky - even though its a sub feature, it should be separate in order to track it and mark it when its completed. Since github can't make sub issues within a task, we'll have to make individual issues for each task. Mark it complete when done to know where were at.

-Nick

**Comment by Arnav-Bhardwaj** [comment]
Completed. since siamak added the js functionality to allow user to add posts.
