### ISSUE TITLE
Add login protected view and restricted password

### ISSUE THREAD

**Issue by SiamakSamie** [Songtone/SOEN341TEAMF#27]
Subfeature of #11 

Viewing permissions based on logged in or not
Password strength

**Comment by JKukulsky** [comment]
Waiting for review of merge #32 to close this issue. Main User Feature issue #11 will then close as all sub-features will be implemented.

**Comment by JKukulsky** [comment]
Merged in #32 Login

Obtained sufficient amount of reviewers. Closing and merging.
