### ISSUE TITLE
Beautification (CSS) of cards

### ISSUE THREAD

**Issue by SiamakSamie** [Songtone/SOEN341TEAMF#30]
Task Breakdown:
-Adjust the color of the card
-Change the design
-Give it some flair
-add hover animation
-add an icon to show which type of job is required
-make the cards appear in a row instead of columns

Pull request: Css Modifcation to make it look decent #37

**Comment by JKukulsky** [comment]
Don't forget to add the specifics of what you coded (hover animation, icon, cards in rows...) to the task breakdown later and make a link to Merge #37
