### ISSUE TITLE
Plan Sprint 3 (create backlog)

### ISSUE THREAD

**Issue by JKukulsky** [Songtone/SOEN341TEAMF#35]
To plan sprint 3 feature we will be implementing.

Possible Sprint 3 Features:

- More pages!
- Full profile page, portfolio section
- Full search
- Sidebar category tree, each category has own page where related posts live
- Rating/liking system ("I Also Want This" button on card)
- Take a job page ("I Will Make This" button on card)
- Make a general Test case
- Logo
- Fix Bugs

**Comment by JKukulsky** [comment]
Ready for review by team. Need to agree on what features we will be taking on, and a rough estimate on who is doing what feature.

**Comment by mohghalayini** [comment]
I agree with this list . Good job josh.

**Comment by Arnav-Bhardwaj** [comment]
Great issues ! we can start dividing these among each other

**Comment by JKukulsky** [comment]
Approved by all.
