### ISSUE TITLE
As a user, I'd like to have a profile page to see my account information

### ISSUE THREAD

**Issue by DJNGattuso** [Songtone/SOEN341TEAMF#46]
- Create a profile page that shows the username 
- #62  Create a button that goes to the user's profile page from anywhere
To consider: have the wants that the user added appear on their profile page and allow them to manage the wants
- #17 user ID
- #64 
- #63 
- #84 
- #102 

Parent: #90 
Points: 7

**Comment by JKukulsky** [comment]
All sub-issues are complete, and all pull requests have been merged into master
