### ISSUE TITLE
Add the 'like a want' feature

### ISSUE THREAD

**Issue by DJNGattuso** [Songtone/SOEN341TEAMF#49]
On the want cards, add a like button that allows other users to like the want
Parent #48 
Points: 2

Acceptance criteria:
- Be able to give a like to an item.
- Be able to view the amount of likes that every item got.
- Be able to unlike the item, but only if the user has liked it before.

**Comment by DarrinFong** [comment]
with branch dev/likes

**Comment by DarrinFong** [comment]
Initial implementation/P-R: #85

**Comment by DarrinFong** [comment]
All acceptance criteria have been met.
