### ISSUE TITLE
Travis should be able to perform to a simple test on the webpage

### ISSUE THREAD

**Issue by DJNGattuso** [Songtone/SOEN341TEAMF#57]
Make a test case that travis could perform to assure the webpage is working

Points: 6

**Comment by DJNGattuso** [comment]
This issue will either make a test that is performed on the entire website or a unit test that we can then perform. Note: a unit test doesn't necessarily need to use travis.

**Comment by DJNGattuso** [comment]
Looked into what needs to be done in terms of writing a test. I need to write a program and reference the file in the "script" section of the Travis.yml file. 

I'll work on making a test tomorrow

**Comment by DJNGattuso** [comment]
Current update: with using laika for a test case...can't seem to get laika to run. With that, there's no real way of knowing if the test case works. In addition, it doesn't seem to be something that runs automatically whenever we push something to the github like the TA wants...I'll do a bit more research in using travis for this

most recent: #87

**Comment by DJNGattuso** [comment]
Moving to sprint 4, the necessary requirements for travis for sprint 3 have been met. This issue is more needed for sprint 4 requirements

**Comment by DJNGattuso** [comment]
@Songtone will look into this with me. We need to find out to run a test through travis. Basically, we need to see what file and language is need and how to call it through the yml script section.

From there, we can write some unit test blocks for different sections of the project

**Comment by DJNGattuso** [comment]
@JKukulsky  @DarrinFong and @Arnav-Bhardwaj - can you guys look into this issue for me. I've been trying to setup spacejam to run the test on travis but I'm getting errors with the setup. 

I'm following setup from here: https://www.npmjs.com/package/spacejam
and referred to this repo that has it done: https://github.com/practicalmeteor/meteor-munit

This is the error i'm getting from the packages.js file that contains the test stuff when running meteor:
![image](https://user-images.githubusercontent.com/25970438/32120083-4d85a0fe-bb25-11e7-8841-b5bb96dcde33.png)

**Comment by DarrinFong** [comment]
Follow branch: https://github.com/Songtone/SOEN341TEAMF/tree/test/travis

**Comment by Arnav-Bhardwaj** [comment]
@DarrinFong  if you are done could you please close this branch

**Comment by DarrinFong** [comment]
Not finished yet, might need to push to sprint 5 depending on if i can get it in the next hour

**Comment by DJNGattuso** [comment]
I will be writing a test on 1 of our website's features in the upcoming days. I have to finish some other work first

**Comment by DJNGattuso** [comment]
recent merged #156
