### ISSUE TITLE
Create a Logo which will be used as a Home Button and put it at the top of the page

### ISSUE THREAD

**Issue by Songtone** [Songtone/SOEN341TEAMF#58]
To create a logo and place it on the nav bar to be used as a home button.
-Create a profile button in nav bar
-Make it go towards the home button
Points: 1

**Comment by mohghalayini** [comment]
Logo's colors should match the style of the website.

**Comment by JKukulsky** [comment]
Thank you Seb for the great logo and the implementation of it.
