### ISSUE TITLE
Add a button on the nav so the user can view/open his profile

### ISSUE THREAD

**Issue by Songtone** [Songtone/SOEN341TEAMF#62]
This can be used from anywhere on the website once the user is logged in. 
Put it on the nav bar right next to the account name or we can have the account name have a drop down.
The drop down can include other things too. For now it will be placed on the nav bar,

**Comment by DJNGattuso** [comment]
#65 merged. It allows the button to bring the user to their profile page

**Comment by DJNGattuso** [comment]
closed because of recent merge
