### ISSUE TITLE
Expand user register input list, to gather more user info when registering for profile page. 

### ISSUE THREAD

**Issue by Arnav-Bhardwaj** [Songtone/SOEN341TEAMF#64]
Working on Branch: dev/expandUserInputFields (5 commits)

The user will be able to add their personal information on the card as mentioned in #63, create a simple form which will allow user to add their details 

Expand user register input list, to gather more user info when registering for profile page. 

**Story Points:** 7

**Acceptance Test:**
The user should be able to click "Fill Profile" and get a pop-up input form. This form should include userId, username, email, first name, last name, city, province, phone number, picture, and skills. This data should then be saved into the UserData Collection.

**Comment by mohghalayini** [comment]
we don't want the user to add a lot of uninformative info, at least 80% of the info should be related to the user's skills and experience.

**Comment by Arnav-Bhardwaj** [comment]
Acceptance Test **PASSED**
