### ISSUE TITLE
Clicking the "Want" button will store the current user's ID in a new collection associated to each ad

### ISSUE THREAD

**Issue by MBastiampillai** [Songtone/SOEN341TEAMF#67]
Every time that this button is clicked, a counter should increment and display the current count in the field on the card.

**Comment by Arnav-Bhardwaj** [comment]
ok that is a very promising start for this feature but I think you should also later  store the username in a collection tied to the ad card, then you can keep track of how many people want the ad from the home page.

**Comment by JKukulsky** [comment]
@MBastiampillai. Title should be more descriptive, as we have already "Add[ed] a "want" button". It should read something like, "Clicking the "Want" button will store the current user's ID in a new collection associated to each ad."

**Comment by MBastiampillai** [comment]
I Had a brief conversation with Siamak, we realized that there was some miscommunication since the want button was actually completed before. We decided that it would be beneficial if I downloaded the pull request, looked at the code and tested it to make sure that it was properly implemented. This is the current task that I am working on.

**Comment by MBastiampillai** [comment]
The code was read and understood. Everything seems to be working fine.

**Comment by JKukulsky** [comment]
Task completed by @SiamakSamie
