### ISSUE TITLE
Create Ad ID's

### ISSUE THREAD

**Issue by JKukulsky** [Songtone/SOEN341TEAMF#69]

**Comment by JKukulsky** [comment]
Update: Just installed msavin:mongol tool to view contents of collections. When I look at post collections, there is already an ID field. See attached picture.
![screen shot 2017-10-12 at 5 24 42 pm](https://user-images.githubusercontent.com/25468272/31519978-4648cffa-af72-11e7-9fc0-8653e83f8edb.png)

**Comment by Songtone** [comment]
Found out the ad cards already had an ID.
