### ISSUE TITLE
Broken Meteor Bable Runtime error in node_modules package 

### ISSUE THREAD

**Issue by Arnav-Bhardwaj** [Songtone/SOEN341TEAMF#71]
Issue is that when used git clone the project folder, meteor is running on cmd but browser page doesn't show the web app running

**Comment by JKukulsky** [comment]
This is currently affecting half of the group.

**Comment by Arnav-Bhardwaj** [comment]
I just checked the error details for the  soen341webapp on the browser. It stated node_modules bable-runtime cant be found and core js. I noticed that the git repo soen341webapp folder doesn't have node_modules folder inside it as "meteor create testapp" would do it.

**Comment by Songtone** [comment]
I have been having this issue as well for about a week. Been trying to fix it but to no avail.

**Comment by Arnav-Bhardwaj** [comment]
I believe who ever is having this issue to just create the local meteor project  and place those nodes_modules files into the nodes_modules on the soen341webapp folder, then place the nodes_modules inside the soen341webapp folder, it worked on my local machine. @Songtone

**Comment by Songtone** [comment]
I will try it once I get home! Thanks for letting me know!
