### ISSUE TITLE
enhancement to searchbar; searching through DB as user types

### ISSUE THREAD

**Issue by SiamakSamie** [Songtone/SOEN341TEAMF#74]
Currently, user can search after pressed enter. We wants a more dynamic search. When each key on the keyboard is pressed, the search list is updated. Enhancement to issue #18

**Comment by Arnav-Bhardwaj** [comment]
@SiamakSamie  if you are done this issue can you close it.

**Comment by Arnav-Bhardwaj** [comment]
After discussion moving to sprint 5
