### ISSUE TITLE
Change the color of the delete button, and have button from "close" to X. 

### ISSUE THREAD

**Issue by Songtone** [Songtone/SOEN341TEAMF#77]
Change the CSS for the delete icon.
Adjusting the ad cards if needed,
Also changed the "close" to a red X.

**Comment by DJNGattuso** [comment]
is the delete icon already merged inside? Or, is there a certain branch that its in that I should use?

**Comment by SiamakSamie** [comment]
It's merged in the master.

**Comment by JKukulsky** [comment]
Closed.

Merged Branch: #79
