### ISSUE TITLE
PPT slide ideas -Midterm Progress

### ISSUE THREAD

**Issue by Arnav-Bhardwaj** [Songtone/SOEN341TEAMF#86]
Project Presentation (Oct. 20):
10 minute presentation, with the entire team
• 5-10 slides covering:
• Intro
• Technologies/design/implementation
• Progress thus far
• Positives & negatives/challenges (w project,
process, etc..)
• (quick) Demo of prototype

**Comment by Arnav-Bhardwaj** [comment]
Slide 1- Intro with names and title - Arnav
Slide 2- MakerHub concept  - Siamak
Slide 3- Technologies (3tire Architecture/Meteor) - Arnav
Slide 4- Design ( Happy face Wire-frame )- Mario
Slide 5- Implementation (Scrum methodology book figure with reference included) - Darren
Slide 6- Progress thus far (screenshot of the main page with search bar working)- Mohamad
Slide 7- Positive (Github organization, how we progressed with sprint 1 to 3)- Nick
Slide 8 - Challenges (check #71 )- Seb
Demo - Josh

**Comment by JKukulsky** [comment]
Add Scrum diagram somewhere

**Comment by Arnav-Bhardwaj** [comment]
Guys check out the slides layout @DarrinFong @mohghalayini @SiamakSamie @Songtone @DJNGattuso @MBastiampillai

**Comment by Arnav-Bhardwaj** [comment]
put the scrum diagram in implementation

**Comment by DJNGattuso** [comment]
Alright awesome! I'll write up my section tomorrow. You gave me a good one ;)

**Comment by JKukulsky** [comment]
Link to Google Slides presentation: [SOEN 341 - Presentation 1](https://docs.google.com/presentation/d/1Ta6jZBQz77XxIWb99If1sSU8PDm4JvNklDrKu1CVf2E/edit?usp=sharing)

**Comment by Arnav-Bhardwaj** [comment]
Completed.
