### ISSUE TITLE
As a user, I would like to see the most liked ad posting

### ISSUE THREAD

**Issue by Arnav-Bhardwaj** [Songtone/SOEN341TEAMF#91]
Created a function that can sort the ad posting. The most popular (most liked), will be shown at the top of the list.

- Apply this function as a result during a search. The most popular ad relating to the search should be shown first.

- Apply this function in the general ad page 

Story Points: 15

**Comment by DarrinFong** [comment]
Acceptance test:
- Typing into the search bar and pressing enter will return top 20 relevant search results
- Search will automatically sort items from most liked (top of page) to least liked (bottom)

**Comment by DarrinFong** [comment]
Finished implementation with commit: c329518

**Comment by DarrinFong** [comment]
Acceptance verification:
- Search does return top 20 relevant results
- Items are sorted according to likes
